# Use vim keybinds
setw -g mode-keys vi

# Enable scrolling with the mouse wheel
set -g mouse on

# Fix colors
set -a terminal-features 'xterm-256color:RGB'

# Move status bar to the top
set -g status-position top

# Clean up right hand side of the status bar
set-option -g status-right ""

# Make background transparent
set -g status-style bg=default

# Increase status-left length (displays session name)
set -g status-left-length 20

# Center window list
set -g status-justify absolute-centre

# --- START: plugins --- 

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# --- END: plugins ---

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
